version: "3.4"
services:
  wireguard:
    build: ./build-wg
    image: "wireguard.wireguard.public.dappnode.eth:0.1.0"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PEERS=dappnode_admin
      - SERVERURL=
      - WIREGUARD_RELEASE=
      - PUID=1000
      - PGID=1000
      - SERVERPORT=51820
      - PEERDNS=172.33.1.2
      - INTERNAL_SUBNET=10.24.0.0
      - ALLOWEDIPS=172.33.0.0/16
    volumes:
      - "wg-config:/config"
      - "/lib/modules:/lib/modules"
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
  api:
    build: ./build-api
    image: "api.wireguard.public.dappnode.eth:0.1.0"
    volumes:
      - "wg-config:/config"
volumes:
  wg-config: {}
