version: "3.4"
services:
  wireguard.public.dappnode.eth:
    build: ./build
    image: "wireguard.public.dappnode.eth:0.1.0"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zagreb
      - SERVERPORT=51820 
      - PEERS=
      - PEERDNS=172.33.1.2 
      - SERVERURL=${_DAPPNODE_GLOBAL_HOSTNAME}
      - INTERNAL_SUBNET=172.33.10.0 
      - ALLOWEDIPS=172.33.0.0/16 
    volumes:
      - config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1